name: Auto-setting milestone on new issue

on:
  issues:
    types: [opened]

jobs:
  auto-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: set milestone to issue
        run: |
          milestone=1 

          echo "Assigning milestone $milestone to the issue..."

          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d "{\"milestone\": \"$milestone\"}"

          echo "Sucesso. Milestone associada a issue ${{ github.event.issue.number }}!"

      - name: Add a comment to the issue
        run: |
          # Comment to be added
          comment="### Obrigado por abrir a issue\n### Verifique os nossos guidelines:\n- [Código de conduta](https://github.com/DevHatt/octopost/blob/master/docs/CODE_OF_CONDUCT.md)\n- [Contribuição](https://github.com/DevHatt/octopost/blob/master/docs/CONTRIBUTING.md)\n- [Guia de Estilo](https://github.com/DevHatt/octopost/blob/master/docs/STYLEGUIDE.md)" 

          # Add the comment to the issue
          echo "Adding comment to the issue..."
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -d "{\"body\": \"$comment\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
